// GET All books
GET http://localhost:3000/products
###
 
//GET Reading now
GET http://localhost:3000/products/1234567
###

//PUT Update a rewiew
PUT http://localhost:3000/products/8765467 
Content-Type: application/json

{
   "id":"8765467",
    "Title": "Evelyn Hugos sju äkta män",
    "Author": "Taylor Jenkins Reid",
    "Rating": "5/5"
}

###
 
//POST Add a new book
POST  http://localhost:3000/products
Content-Type: application/json
 
{
 "id":"",
   "Title": "",
   "Author": "",
   "Rating": ""
}
###
 
//DELETE a book
DELETE http://localhost:3000/products/1234567
###
 
